type: button
widget_id: nist_security_baseline-audit_files_owner_configure-button-widget
api_url: /module/nist_security_baseline/get_list/audit_files_owner_configure
i18n_title: nist_security_baseline.widget.audit_files_owner_configure_title
icon: fa-laptop
listing_link: /show/listing/nist_security_baseline/nist_security_baseline
buttons:
  - label: "0"
    i18n_label: nist_security_baseline.widget.fail
    class: btn-danger
  - label: "1"
    i18n_label: nist_security_baseline.widget.pass
    class: btn-success
    